### PR TITLE
Mqtt bridge

### PR DESCRIPTION
**Pull request by Tobias-Fischer**

### CODE REVIEW

**Comment by wolfv** [comment]
It looks like they have additional Python dependencies here: https://github.com/groove-x/mqtt_bridge/blob/master/requirements.txt

That should ideally be patched out, I guess.

**Comment by wolfv** [comment]
They are installing them here: https://github.com/groove-x/mqtt_bridge/blob/84a9f549fed94f51dda7fb4c773f2a7c44b4eaf0/CMakeLists.txt#L22

**Comment by wolfv** [comment]
For this one we might need a recipe on conda-forge: https://pypi.org/project/Inject/

**Comment by wolfv** [comment]
https://github.com/conda-forge/staged-recipes/pull/14593

**Comment by Tobias-Fischer** [comment]
Ah that required more work than I expected! I can finish the PR on Monday if you want; thanks for taking care of the inject package.

**Comment by Tobias-Fischer** [comment]
See https://github.com/RoboStack/vinca/commit/039964fb4fda2118725d74854ed92db2ea8ab9b1 that adds required run_deps.

**Comment by wolfv** [comment]
I think we could inject those dependencies in the patch/dependencies.yaml file as well :)

**Comment by Tobias-Fischer** [comment]
See https://github.com/RoboStack/vinca/issues/8re this :)

**Pull request merged**
