### PR TITLE
Add jsk visualisation 

### PR DESCRIPTION
**Pull request by hsparkastro**

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
Needs https://github.com/mamba-org/boa/pull/357

**Comment by Tobias-Fischer** [comment]
Hi @anand-bala @wolfv - it seems like the cdt_name is still not respected. Any idea why? I've pulled boa from the `main` branch.

**Comment by anand-bala** [comment]
I think the potential issue here is with `numpy 1.20.*` constraint. Running `mamba repoquery depends ros-noetic-rosbag` says that the version that the package is built with is `numpy 1.25.2`. I am not sure if that is the exact problem, but it is more than likely.

Is the version pinned to `1.20.*` in the `conda_build_config.yaml` file for a specific reason? Or is it ok to loosen the constraint to `1.*`?

**Comment by hsparkastro** [comment]
Yay!!! Thanks @Tobias-Fischer!

**Comment by Tobias-Fischer** [comment]
It still needs more work unfortunately .. the build passes locally but not on CI for some reason :(

**Comment by Tobias-Fischer** [comment]
Packages are up now

**Pull request merged**
