### PR TITLE
Fix OS X usage with macOS

### PR DESCRIPTION
**Pull request by traversaro**
Minor nitpick: the official name of the operating systems in Mac computers is macOS since a few years (2016, see https://en.wikipedia.org/wiki/MacOS#macOS_10.12_Sierra). I think is cleaner to refer to it with its official name in user-facing documentation.

### CODE REVIEW

**Comment by traversaro** [comment]
cc @wolfv @Tobias-Fischer

**Comment by Tobias-Fischer** [comment]
Good point! Would you mind fixing the badges, too?

**Comment by traversaro** [comment]
> 
> 
> Good point! Would you mind fixing the badges, too?

Done: https://github.com/traversaro/ros-noetic/commit/33492dc1e72467c6aedac1f9b5dcc520d4d34039 .

**Comment by Tobias-Fischer** [comment]
Thanks @traversaro!

**Pull request merged**
