### PR TITLE
added patch for apriltag-ros (tested only on macos)

### PR DESCRIPTION
**Pull request by raghavauppuluri13**
Builds fine after patch. There was an issue with an extra namespace that is added for ros2 that isn't needed for ros-noetic in the CMakeLists.txt

### CODE REVIEW

**Comment by traversaro** [comment]
I guess this patch can be removed once a apriltag is bumped to v3.1.6, see https://github.com/AprilRobotics/apriltag/pull/167 and https://github.com/AprilRobotics/apriltag/issues/166 . However, until then the fix seems good to go!

**Comment by Tobias-Fischer** [comment]
Could you please modify the vinca_*.yaml files so that this package is rebuild?

**Comment by Tobias-Fischer** [comment]
The patch does not apply cleanly @raghavauppuluri13

**Comment by Tobias-Fischer** [comment]
Might be easier to simply rebuild the package after https://github.com/ros/rosdistro/pull/30812 will have been merged in.

**Comment by raghavauppuluri13** [comment]
Yes, that would work. Its weird how my patch isn't working though. can't really deduce what the issue is.

**Pull request closed without merging**
