### PR TITLE
Fix #98 (do not ever use deb install-layout)

### LINKED ISSUE #98: ros-noetic-catkin and install-layout
I am locally using RoboStack to debug a catkin package which contains a catkin-type `setup.py` and uses `catkin_python_setup()`. Alas, it fails to install due to the `--install-layout=deb` option used in catkin (upstream issue describing the same problem: https://github.com/ros/catkin/issues/863). 

Have you tried compiling/installing catkin packages which include a Python package? 

The `SETUPTOOLS_DEB_LAYOUT` option could potentially be a workaround unless it affects something else (dist-packages vs site-packages for instance). I saw the [patch file](https://github.com/RoboStack/ros-noetic/blob/master/patch/ros-noetic-catkin.patch) for ros-noetic-catkin but no change that would potentially address this issue?

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Fixes #98 

Thanks @wxmerkt for reporting this issue.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
This is ready to go @wolfv

**Comment by Tobias-Fischer** [comment]
Hi @wolfv - shall we merge this?

**Comment by wolfv** [comment]
Yes looks good to me!

**Comment by wolfv** [comment]
If we want something upstreamable we could check for the CONDA_PREFIX environment variable

**Pull request merged**
