### PR TITLE
adding rosmon to all arch

### PR DESCRIPTION
**Pull request by alaurenzi**
Trying to add `rosmon` to RoboStack.
This is a C++ based drop-in replacement for `roslaunch` with additional functionalities.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
We might need sth like https://reviews.llvm.org/D39717

**Comment by alaurenzi** [comment]
Thanks @Tobias-Fischer I'll have a look, try to test it locally (at least on Linux-64), and update this PR

**Comment by alaurenzi** [comment]
Added patch as suggested, `rosmon-core` now builds fine on my machine. 

Getting an error when trying to compile `rqt-rosmon` though. It involves `ros-distro-mutex`:
```
RuntimeError: Solver could not find solution.Mamba failed to solve:
 - numpy 1.19.*
 - pip
 - pkg-config
 - python 3.9.* *_cpython
 - ros-distro-mutex 0.3.* noetic
 - ros-noetic-catkin
 - ros-noetic-rosmon-core
 - ros-noetic-rqt-rosmon
 - libstdcxx-ng >=12
 - libgcc-ng >=12
 - libgcc-ng >=12

with channels:

The reported errors are:
- Encountered problems while solving:
-   - package ros-noetic-rqt-rosmon-2.4.0-py38h7d895da_12 requires ros-distro-mutex 0.2.*, but none of the providers can be installed
```

Unfortunately I don't have enough experience to understand where this comes from. Any pointers you might give me?

**Comment by alaurenzi** [comment]
Update: it was fixed by adding `rqt-rosmon` to `vinca.yaml`.

**Comment by Tobias-Fischer** [comment]
Thanks @alaurenzi! Do you care about the other platforms? If not, I suggest to reverse the changes and I’m happy to merge just linux-64

**Comment by alaurenzi** [comment]
Yes let's do as you say. I'm also not familiar with other platforms, let alone how cross-compilation is handled by conda!

**Pull request merged**
