### PR TITLE
Add sound_play to linux

### PR DESCRIPTION
**Pull request by peci1**
This is a simple text-to-speech ROS package. Great to be used e.g. on Steam Deck to allow the robot to speak to the operator.

I think this will need specifying more dependencies, mostly festival package. I haven't found it in conda. Also, the Lua script [text2wave installed by festival needs this patch](https://github.com/festvox/festival/issues/33) to support sound_play:

    sudo sed -ibak 's/wholeutt (utt.synth (Utterance Text ""))/wholeutt (Utterance Text "")/' /usr/bin/text2wave

Last, to get sound_play built from source working, I also needed this workaround:

    ln -s /usr/lib/alsa-lib/libasound_module_pcm_pipewire.so /home/deck/mambaforge/envs/ros_env/lib/alsa-lib/libasound_module_pcm_pipewire.so

Not sure how to do this properly...

### CODE REVIEW

**Comment by peci1** [comment]
Hmm, as expected, I see

     Unsatisfied dependencies: {'flite', 'festival', 'python3-gi'}

in the build logs of CI. How can I help with that?

**Comment by Tobias-Fischer** [comment]
I think we can simply map `python3-gi` to `pygobject` in the https://github.com/RoboStack/ros-noetic/blob/master/conda.yaml and https://github.com/RoboStack/ros-noetic/blob/master/robostack.yaml files.

For flite and festival, to properly do things, we would need to add conda recipes. These can be added via https://github.com/conda-forge/staged-recipes

That said, all these three dependencies seem to be run dependencies only, and do not seem to be used during build time. So we could just merge this PR, and then rely on the Ubuntu-shipped packages. Not nice, but it would work.

**Comment by peci1** [comment]
Okay. I've added pygobject definitions to this PR. There are however some CI failures, so maybe something more is needed?

And I've started to (slowly) provide the other libraries through conda-forge: https://github.com/conda-forge/staged-recipes/pull/21892 . As I'm new to this ecosystem, it might take some time until all of them are satisfied.

**Comment by Tobias-Fischer** [comment]
Ah, there's an annoying thing happening where it reads the conda.yaml/robostack.yaml from the main branch.

**Comment by wolfv** [comment]
Thanks for the contribution @peci1 – happy to help with festival on conda-forge.

**Comment by peci1** [comment]
@wolfv Thanks, I'll ping you there when I have something ;)

**Comment by Tobias-Fischer** [comment]
@peci1 do you want me to merge here, or wait till you have festival on conda-forge?

**Comment by peci1** [comment]
Please, go on. festival might take some time, and as you've mentioned, the workaround is to use the host system version (it only uses executables from festival, so it works flawlessly).

**Comment by peci1** [comment]
> Thanks for the contribution @peci1 – happy to help with festival on conda-forge.

Thanks for the offer, @wolfv . I have a fix for libestools https://github.com/conda-forge/libestools-feedstock/pull/1 where I need second eyes. And I've also already prepared festival https://github.com/conda-forge/staged-recipes/pull/21974, however there are some strange dependency problems I encounter in local builds. I'll be glad if you find some time to help.

**Comment by peci1** [comment]
@Tobias-Fischer I've finished adding festival and festvox-kallpc16k packages to conda-forge. What's the correct way to start using them in robostack? Should I add the rosdep key to conda.yaml and robostack.yaml?

**Comment by Tobias-Fischer** [comment]
Awesome, yes please :).

**Pull request merged**
