### PR TITLE
add hector-trajecotry-server to linux

### PR DESCRIPTION
**Pull request by gftabor**
as suggested on gitter add hector trajectory server to linux.

My intuition would be to add all the hector packages to be run but I believe the goal is to keep the list small?

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
Feel free to add more hector packages @gftabor - if people are using these packages with RoboStack, I am happy to build them.

**Comment by Tobias-Fischer** [comment]
Thanks @gftabor - any chance you could please add the same packages to the other `vinca_*.yaml` files so we have rough feature parity across the platforms?

**Comment by gftabor** [comment]
That's a good point...

**Comment by Tobias-Fischer** [comment]
Thanks @gftabor

**Pull request merged**
