### PR TITLE
Fix cv_bridge CMake exports

### PR DESCRIPTION
**Pull request by peci1**

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
Have you tried locally to see whether this achieves the desired effect?

**Comment by peci1** [comment]
Yes, I'm trying right now. It does not. I'm figuring out what's wrong.

So far, it looks that somewhere around https://github.com/ros/catkin/blob/ff31d451ce1c68d47bc058a4693aad6c0fb63a43/cmake/catkin_package.cmake#L258C3-L258C42 there are libraries disappearing. Before this, `OpenCV_LIBRARIES` contains the whole lot of libs, but relative. After that line, they should be converted to absolute, but instead, they disappear.

**Comment by peci1** [comment]
Also, keeping the `find_package(OpenCV 4 QUIET)` is important. It pulls all installed OpenCV libs into `OpenCV_LIBRARIES`, and the second call with required components just appends those components. I think the logic is: "provide as many libraries as possible, but fail if at least the two listed components are not present".

**Comment by peci1** [comment]
@Tobias-Fischer This should fix #424, but I don't understand the mac and win segfaults. I also did the ruamel.yaml fix for GH Actions PRs.

**Comment by aravindsiv** [comment]
Hi @peci1 ,

I want to use this patch since I'm facing a similar issue to #424 (I have OpenCV missing symbol errors with `cmake`). What would be the best way to go about this?

**Comment by peci1** [comment]
Hi, I'm not able to help here. You would probably need to build the packages locally, but how to do that is a question I can't answer. You should read the documentation and try to understand the local build process.

**Comment by Tobias-Fischer** [comment]
I've added this fix to #418

**Pull request closed without merging**
