### PR TITLE
Full rebuild

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Mainly to check for conflicts in the patches ..

### CODE REVIEW

**Comment by wolfv** [comment]
@Tobias-Fischer I'll leave it running until this times out and then IMO we can merge?!

**Comment by Tobias-Fischer** [comment]
Shall we try and fix `LINK : fatal error LNK1181: cannot open input file 'Qt5Core_conda_conda.lib'` and then merge? Happy either way though, it's very unlikely that it just builds all packages in one go without issues I guess ..

**Comment by Tobias-Fischer** [comment]
I think it's just a matter of removing the patch_sipconfig.py which is not needed anymore. That's easy enough, we might as well do that - I can't remember where this is being pulled in though?

Also, shall we merge https://github.com/RoboStack/vinca/pull/6 before rebuilding?

**Comment by wolfv** [comment]
I've merged it, let's hope we set up the boa solver correctly :) only micromamba 0.8 will support these virtual packages, btw (it's out but the release needs some fixes)

**Comment by wolfv** [comment]
I don't remember much about the patch sipconfig either right now... I can look at this tomorrow if you don't get to it before

**Comment by Tobias-Fischer** [comment]
Looking good now. Shall we merge?

**Comment by wolfv** [comment]
This is going to be fun

**Pull request merged**
