### PR TITLE
added imu-tools

### PR DESCRIPTION
**Pull request by sonelu**
Included `imu-tools` for rebuild under Python 3.9.

### CODE REVIEW

**Comment by wolfv** [comment]
I think the osx-arm64 and linux-aarch64 issues might be related to cross-compilation?

Windows looks more serious though.

**Comment by wolfv** [comment]
It fails at the moc-generation stage.

**Comment by sonelu** [comment]
I've noticed - but is not related to `imu-tools`.

- linux-aarch64 fails because of rviz
- osx-arm64 fails in python_qt_binding
- win-64 fails in librviz_sip

Should I comment out all the other packages and leave only imu-tools? (As a matter of fact, should this be the procedure - comment out the previously built packages and add the desired new packages).

**Comment by sonelu** [comment]
`imu-tools` include an rviz plugin and therefore lists that as a dependency. CI pulls rviz and since a new version was released in the meantime (1.14.14) it will try to build that first. Sincerely, I'm not ready to go that rabbit hole at this moment (I've installed the packet locally in my catkin workspace which is fine for the time being).

But this raises an interesting question: can the CI be optimised so that it doesn't build dependencies, unless they are pinned and those versions are not already built? In this case for instance it seems like a waste that the build for macos has successfully build rviz 1.14.14 but not pushed it to robostack because it was not one of the artefacts requested by vinca. And in the case of the the failed jobs it stops a fairly simple package from build.

**Comment by Tobias-Fischer** [comment]
Hmm .. @wolfv just introduced the version check for #246 ;).

The best way forward is to have more regular rebuilds that will hopefully become more and more seamless. But for that we need to set up our CI a bit better - at the moment the 1 hour build limit is really a pain. Someone sponsored us (many many thanks!) via GitHub sponsors so we have a bit of money for a custom CI, but we need the time to set it up.

**Comment by Tobias-Fischer** [comment]
I'm happy to merge this without building on aarch64 (simply undo the changes in the relevant file). Unless you need it on aarch ..

**Comment by wolfv** [comment]
@Tobias-Fischer is there a chance aarch64 works when building on the native hardware?

**Comment by wolfv** [comment]
let's merge and find out?! :)

**Comment by Tobias-Fischer** [comment]
Could well be that a native compile works .. are you happy to give it a shot?

**Comment by wolfv** [comment]
Looks like everything is going fine in the Azure pipelines. 
Thanks @sonelu for persisting and your contributions!

**Comment by sonelu** [comment]
The only problem is that we now have rviz 1.14.14 only for linux-64 and osx-64, for windows and aarch64 they are on 1.14.13; we will have the same problems when we would want to have those built.

**Pull request merged**
