### PR TITLE
mavros windows continued

### PR DESCRIPTION
**Pull request by Tobias-Fischer**

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
I tried to get this to compile, but I'm giving up now. Does anyone know where this error might come from?
```
%SRC_DIR%\ros-noetic-libmavconn\src\work\src\serial.cpp(118): error C2059: syntax error: '.'
```
Relevant code:
```
	io_thread = std::thread([this] () {
				//utils::set_this_thread_name("mserial%zu", conn_id);
				io_service.run();
			});
```
I already commented out the thread naming stuff, so I am really not sure why there is a syntax error.

It would be cool to get this to run on Windows :)

/cc @wolfv @traversaro

**Comment by traversaro** [comment]
Not 100% sure, but often this really strange syntax errors just on Windows (or just on some platform, for example VxWorks) are actually due to some macro shadowing a proper C++ identifier.

**Comment by wolfv** [comment]
weird, it says thread is not a member of boost? Is it just missing an include there?

**Comment by Tobias-Fischer** [comment]
Yes, that's my very latest attempt. It's just missing an include indeed - I'll have another quick go at it tomorrow (but feel free to test before that :))

**Comment by wolfv** [comment]
I think this problem is that CLOCK_MONOTONIC is a Unix thing, so basically their code needs fixing... maybe @seanyen has experience with mavros and can help us out? Or we could open an issue on their repo?

**Comment by Tobias-Fischer** [comment]
Yeah. I've gotten quite far with the Windows fixing. My thought was to get a basic version compiled (without plugins that don't work), then open pull requests upstream and see whether they're interested at all. What do you think?

**Comment by traversaro** [comment]
> 
> 
> Yeah. I've gotten quite far with the Windows fixing. My thought was to get a basic version compiled (without plugins that don't work), then open pull requests upstream and see whether they're interested at all. What do you think?

I totally agree!

**Pull request merged**
