### PR TITLE
[nofix] Add realsense-camera on Windows

### PR DESCRIPTION
**Pull request by Tobias-Fischer**

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@wolfv @traversaro - any ideas how to fix this?

```
[18/18] Linking CXX shared library devel\bin\realsense2_camera.dll
FAILED: devel/bin/realsense2_camera.dll devel/lib/realsense2_camera.lib 
cmd.exe /C "cmd.exe /C "C:\Miniconda\conda-bld\ros_1621921161892\_build_env\Library\bin\cmake.exe -E __create_def C:\Miniconda\conda-bld\ros_1621921161892\work\build\CMakeFiles\realsense2_camera.dir\.\exports.def C:\Miniconda\conda-bld\ros_1621921161892\work\build\CMakeFiles\realsense2_camera.dir\.\exports.def.objs && cd C:\Miniconda\conda-bld\ros_1621921161892\work\build" && C:\Miniconda\conda-bld\ros_1621921161892\_build_env\Library\bin\cmake.exe -E vs_link_dll --intdir=CMakeFiles\realsense2_camera.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~1\2019\ENTERP~1\VC\Tools\MSVC\1416~1.270\bin\HostX64\x64\link.exe /nologo @CMakeFiles\realsense2_camera.rsp  /out:devel\bin\realsense2_camera.dll /implib:devel\lib\realsense2_camera.lib /pdb:devel\bin\realsense2_camera.pdb /dll /version:0.0 /machine:x64 /INCREMENTAL:NO  /DEF:CMakeFiles\realsense2_camera.dir\.\exports.def  && cd ."
LINK: command "C:\PROGRA~2\MICROS~1\2019\ENTERP~1\VC\Tools\MSVC\1416~1.270\bin\HostX64\x64\link.exe /nologo @CMakeFiles\realsense2_camera.rsp /out:devel\bin\realsense2_camera.dll /implib:devel\lib\realsense2_camera.lib /pdb:devel\bin\realsense2_camera.pdb /dll /version:0.0 /machine:x64 /INCREMENTAL:NO /DEF:CMakeFiles\realsense2_camera.dir\.\exports.def /MANIFEST /MANIFESTFILE:devel\bin\realsense2_camera.dll.manifest" failed (exit code 1169) with the following output:
realsense-file.lib(time.cpp.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in realsense_node_factory.cpp.obj
realsense-file.lib(uncompressed_stream.cpp.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in realsense_node_factory.cpp.obj
realsense-file.lib(duration.cpp.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in realsense_node_factory.cpp.obj
realsense-file.lib(stream.cpp.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in realsense_node_factory.cpp.obj
realsense-file.lib(lz4_stream.cpp.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in realsense_node_factory.cpp.obj
realsense-file.lib(chunked_file.cpp.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in realsense_node_factory.cpp.obj
msvcprt.lib(MSVCP140.dll) : error LNK2005: "public: __cdecl std::_Locinfo::_Locinfo(char const *)" (??0_Locinfo@std@@QEAA@PEBD@Z) already defined in realsense-file.lib(time.cpp.obj)
msvcprt.lib(MSVCP140.dll) : error LNK2005: "public: __cdecl std::_Locinfo::~_Locinfo(void)" (??1_Locinfo@std@@QEAA@XZ) already defined in realsense-file.lib(time.cpp.obj)
msvcprt.lib(MSVCP140.dll) : error LNK2005: "public: struct _Cvtvec __cdecl std::_Locinfo::_Getcvt(void)const " (?_Getcvt@_Locinfo@std@@QEBA?AU_Cvtvec@@XZ) already defined in realsense-file.lib(time.cpp.obj)
msvcprt.lib(MSVCP140.dll) : error LNK2005: "public: __cdecl std::locale::id::operator unsigned __int64(void)" (??Bid@locale@std@@QEAA_KXZ) already defined in realsense-file.lib(time.cpp.obj)
msvcprt.lib(MSVCP140.dll) : error LNK2005: "protected: __cdecl std::locale::facet::facet(unsigned __int64)" (??0facet@locale@std@@IEAA@_K@Z) already defined in realsense-file.lib(time.cpp.obj)
msvcprt.lib(MSVCP140.dll) : error LNK2005: "protected: virtual __cdecl std::locale::facet::~facet(void)" (??1facet@locale@std@@MEAA@XZ) already defined in realsense-file.lib(time.cpp.obj)
msvcprt.lib(MSVCP140.dll) : error LNK2005: "public: static unsigned __int64 __cdecl std::ctype<char>::_Getcat(class std::locale::facet const * *,class std::locale const *)" (?_Getcat@?$ctype@D@std@@SA_KPEAPEBVfacet@locale@2@PEBV42@@Z) already defined in realsense-file.lib(time.cpp.obj)
msvcprt.lib(MSVCP140.dll) : error LNK2005: "protected: __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::basic_streambuf<char,struct std::char_traits<char> >(void)" (??0?$basic_streambuf@DU?$char_traits@D@std@@@std@@IEAA@XZ) already defined in realsense-file.lib(uncompressed_stream.cpp.obj)
msvcprt.lib(MSVCP140.dll) : error LNK2005: "public: virtual __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::~basic_streambuf<char,struct std::char_traits<char> >(void)" (??1?$basic_streambuf@DU?$char_traits@D@std@@@std@@UEAA@XZ) already defined in realsense-file.lib(uncompressed_stream.cpp.obj)
msvcprt.lib(MSVCP140.dll) : error LNK2005: "public: int __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::sputc(char)" (?sputc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QEAAHD@Z) already defined in realsense-file.lib(time.cpp.obj)
msvcprt.lib(MSVCP140.dll) : error LNK2005: "public: __int64 __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::sputn(char const *,__int64)" (?sputn@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QEAA_JPEBD_J@Z) already defined in realsense-file.lib(time.cpp.obj)
msvcprt.lib(MSVCP140.dll) : error LNK2005: "protected: char * __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::_Pninc(void)" (?_Pninc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@IEAAPEADXZ) already defined in realsense-file.lib(time.cpp.obj)
msvcprt.lib(MSVCP140.dll) : error LNK2005: "public: virtual __cdecl std::basic_ios<char,struct std::char_traits<char> >::~basic_ios<char,struct std::char_traits<char> >(void)" (??1?$basic_ios@DU?$char_traits@D@std@@@std@@UEAA@XZ) already defined in realsense-file.lib(uncompressed_stream.cpp.obj)
msvcprt.lib(MSVCP140.dll) : error LNK2005: "public: void __cdecl std::basic_ios<char,struct std::char_traits<char> >::setstate(int,bool)" (?setstate@?$basic_ios@DU?$char_traits@D@std@@@std@@QEAAXH_N@Z) already defined in realsense-file.lib(time.cpp.obj)
msvcprt.lib(MSVCP140.dll) : error LNK2005: "public: char __cdecl std::basic_ios<char,struct std::char_traits<char> >::widen(char)const " (?widen@?$basic_ios@DU?$char_traits@D@std@@@std@@QEBADD@Z) already defined in realsense-file.lib(uncompressed_stream.cpp.obj)
msvcprt.lib(MSVCP140.dll) : error LNK2005: "protected: __cdecl std::basic_ios<char,struct std::char_traits<char> >::basic_ios<char,struct std::char_traits<char> >(void)" (??0?$basic_ios@DU?$char_traits@D@std@@@std@@IEAA@XZ) already defined in realsense-file.lib(uncompressed_stream.cpp.obj)
msvcprt.lib(MSVCP140.dll) : error LNK2005: "public: __cdecl std::basic_ostream<char,struct std::char_traits<char> >::basic_ostream<char,struct std::char_traits<char> >(class std::basic_streambuf<char,struct std::char_traits<char> > *,bool)" (??0?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@PEAV?$basic_streambuf@DU?$char_traits@D@std@@@1@_N@Z) already defined in realsense-file.lib(uncompressed_stream.cpp.obj)
msvcprt.lib(MSVCP140.dll) : error LNK2005: "public: virtual __cdecl std::basic_ostream<char,struct std::char_traits<char> >::~basic_ostream<char,struct std::char_traits<char> >(void)" (??1?$basic_ostream@DU?$char_traits@D@std@@@std@@UEAA@XZ) already defined in realsense-file.lib(uncompressed_stream.cpp.obj)
msvcprt.lib(MSVCP140.dll) : error LNK2005: "public: void __cdecl std::basic_ostream<char,struct std::char_traits<char> >::_Osfx(void)" (?_Osfx@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAAXXZ) already defined in realsense-file.lib(time.cpp.obj)
msvcprt.lib(MSVCP140.dll) : error LNK2005: "public: class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl std::basic_ostream<char,struct std::char_traits<char> >::operator<<(int)" (??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAAAEAV01@H@Z) already defined in realsense-file.lib(time.cpp.obj)
msvcprt.lib(MSVCP140.dll) : error LNK2005: "public: class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl std::basic_ostream<char,struct std::char_traits<char> >::operator<<(unsigned int)" (??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAAAEAV01@I@Z) already defined in realsense-file.lib(time.cpp.obj)
msvcprt.lib(MSVCP140.dll) : error LNK2005: "public: class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl std::basic_ostream<char,struct std::char_traits<char> >::operator<<(unsigned __int64)" (??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAAAEAV01@_K@Z) already defined in realsense-file.lib(uncompressed_stream.cpp.obj)
msvcprt.lib(MSVCP140.dll) : error LNK2005: "public: class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl std::basic_ostream<char,struct std::char_traits<char> >::flush(void)" (?flush@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAAAEAV12@XZ) already defined in realsense-file.lib(time.cpp.obj)
msvcprt.lib(MSVCP140.dll) : error LNK2005: "protected: void __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::_Init(void)" (?_Init@?$basic_streambuf@DU?$char_traits@D@std@@@std@@IEAAXXZ) already defined in realsense-file.lib(uncompressed_stream.cpp.obj)
msvcprt.lib(MSVCP140.dll) : error LNK2005: "protected: virtual __int64 __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::xsgetn(char *,__int64)" (?xsgetn@?$basic_streambuf@DU?$char_traits@D@std@@@std@@MEAA_JPEAD_J@Z) already defined in realsense-file.lib(uncompressed_stream.cpp.obj)
msvcprt.lib(MSVCP140.dll) : error LNK2005: "protected: virtual __int64 __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::xsputn(char const *,__int64)" (?xsputn@?$basic_streambuf@DU?$char_traits@D@std@@@std@@MEAA_JPEBD_J@Z) already defined in realsense-file.lib(uncompressed_stream.cpp.obj)
libcpmt.lib(locale0.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in realsense_node_factory.cpp.obj
libcpmt.lib(locale0.obj) : error LNK2005: "void __cdecl std::_Facet_Register(class std::_Facet_base *)" (?_Facet_Register@std@@YAXPEAV_Facet_base@1@@Z) already defined in msvcprt.lib(locale0_implib.obj)
libcpmt.lib(locale0.obj) : error LNK2005: "private: static class std::locale::_Locimp * __cdecl std::locale::_Getgloballocale(void)" (?_Getgloballocale@locale@std@@CAPEAV_Locimp@12@XZ) already defined in msvcprt.lib(MSVCP140.dll)
libcpmt.lib(locale0.obj) : error LNK2005: "private: static class std::locale::_Locimp * __cdecl std::locale::_Init(bool)" (?_Init@locale@std@@CAPEAV_Locimp@12@_N@Z) already defined in msvcprt.lib(MSVCP140.dll)
libcpmt.lib(locale0.obj) : error LNK2005: "public: static void __cdecl std::_Locinfo::_Locinfo_ctor(class std::_Locinfo *,char const *)" (?_Locinfo_ctor@_Locinfo@std@@SAXPEAV12@PEBD@Z) already defined in msvcprt.lib(MSVCP140.dll)
libcpmt.lib(locale0.obj) : error LNK2005: "public: static void __cdecl std::_Locinfo::_Locinfo_dtor(class std::_Locinfo *)" (?_Locinfo_dtor@_Locinfo@std@@SAXPEAV12@@Z) already defined in msvcprt.lib(MSVCP140.dll)
libcpmt.lib(locale.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in realsense_node_factory.cpp.obj
libcpmt.lib(locale.obj) : error LNK2005: "public: static unsigned __int64 __cdecl std::codecvt<char,char,struct _Mbstatet>::_Getcat(class std::locale::facet const * *,class std::locale const *)" (?_Getcat@?$codecvt@DDU_Mbstatet@@@std@@SA_KPEAPEBVfacet@locale@2@PEBV42@@Z) already defined in msvcprt.lib(MSVCP140.dll)
libcpmt.lib(locale.obj) : error LNK2005: "public: int __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::sbumpc(void)" (?sbumpc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QEAAHXZ) already defined in msvcprt.lib(MSVCP140.dll)
libcpmt.lib(locale.obj) : error LNK2005: "public: int __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::sgetc(void)" (?sgetc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QEAAHXZ) already defined in msvcprt.lib(MSVCP140.dll)
libcpmt.lib(iosptrs.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in realsense_node_factory.cpp.obj
libcpmt.lib(xthrow.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in realsense_node_factory.cpp.obj
libcpmt.lib(xthrow.obj) : error LNK2005: "void __cdecl std::_Xbad_alloc(void)" (?_Xbad_alloc@std@@YAXXZ) already defined in msvcprt.lib(MSVCP140.dll)
libcpmt.lib(xthrow.obj) : error LNK2005: "void __cdecl std::_Xbad_function_call(void)" (?_Xbad_function_call@std@@YAXXZ) already defined in msvcprt.lib(MSVCP140.dll)
libcpmt.lib(xthrow.obj) : error LNK2005: "void __cdecl std::_Xinvalid_argument(char const *)" (?_Xinvalid_argument@std@@YAXPEBD@Z) already defined in msvcprt.lib(MSVCP140.dll)
libcpmt.lib(xthrow.obj) : error LNK2005: "void __cdecl std::_Xlength_error(char const *)" (?_Xlength_error@std@@YAXPEBD@Z) already defined in msvcprt.lib(MSVCP140.dll)
libcpmt.lib(xthrow.obj) : error LNK2005: "void __cdecl std::_Xout_of_range(char const *)" (?_Xout_of_range@std@@YAXPEBD@Z) already defined in msvcprt.lib(MSVCP140.dll)
libcpmt.lib(xthrow.obj) : error LNK2005: "void __cdecl std::_Xregex_error(enum std::regex_constants::error_type)" (?_Xregex_error@std@@YAXW4error_type@regex_constants@1@@Z) already defined in msvcprt.lib(MSVCP140.dll)
libcpmt.lib(wlocale.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in realsense_node_factory.cpp.obj
libcpmt.lib(wlocale.obj) : error LNK2005: "public: struct _Collvec __cdecl std::_Locinfo::_Getcoll(void)const " (?_Getcoll@_Locinfo@std@@QEBA?AU_Collvec@@XZ) already defined in msvcprt.lib(MSVCP140.dll)
libcpmt.lib(wlocale.obj) : error LNK2005: "public: unsigned short const * __cdecl std::_Locinfo::_W_Getdays(void)const " (?_W_Getdays@_Locinfo@std@@QEBAPEBGXZ) already defined in msvcprt.lib(MSVCP140.dll)
libcpmt.lib(wlocale.obj) : error LNK2005: "public: unsigned short const * __cdecl std::_Locinfo::_W_Getmonths(void)const " (?_W_Getmonths@_Locinfo@std@@QEBAPEBGXZ) already defined in msvcprt.lib(MSVCP140.dll)
libcpmt.lib(xlocale.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in realsense_node_factory.cpp.obj
libcpmt.lib(xlocale.obj) : error LNK2005: "public: struct _Collvec __cdecl std::_Locinfo::_Getcoll(void)const " (?_Getcoll@_Locinfo@std@@QEBA?AU_Collvec@@XZ) already defined in msvcprt.lib(MSVCP140.dll)
libcpmt.lib(xlocale.obj) : error LNK2005: "public: unsigned short const * __cdecl std::_Locinfo::_W_Getdays(void)const " (?_W_Getdays@_Locinfo@std@@QEBAPEBGXZ) already defined in msvcprt.lib(MSVCP140.dll)
libcpmt.lib(xlocale.obj) : error LNK2005: "public: unsigned short const * __cdecl std::_Locinfo::_W_Getmonths(void)const " (?_W_Getmonths@_Locinfo@std@@QEBAPEBGXZ) already defined in msvcprt.lib(MSVCP140.dll)
libcpmt.lib(xlocale.obj) : error LNK2005: "public: int __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::sbumpc(void)" (?sbumpc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QEAAHXZ) already defined in msvcprt.lib(MSVCP140.dll)
libcpmt.lib(xlocale.obj) : error LNK2005: "public: int __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::sgetc(void)" (?sgetc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QEAAHXZ) already defined in msvcprt.lib(MSVCP140.dll)
libcpmt.lib(xlock.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in realsense_node_factory.cpp.obj
libcpmt.lib(xlock.obj) : error LNK2005: "public: __cdecl std::_Lockit::_Lockit(int)" (??0_Lockit@std@@QEAA@H@Z) already defined in msvcprt.lib(MSVCP140.dll)
libcpmt.lib(xlock.obj) : error LNK2005: "public: __cdecl std::_Lockit::~_Lockit(void)" (??1_Lockit@std@@QEAA@XZ) already defined in msvcprt.lib(MSVCP140.dll)
libcpmt.lib(xstrcoll.obj) : error LNK2005: _Strcoll already defined in msvcprt.lib(MSVCP140.dll)
libcpmt.lib(xdateord.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in realsense_node_factory.cpp.obj
libcpmt.lib(xwctomb.obj) : error LNK2005: _Getcvt already defined in msvcprt.lib(MSVCP140.dll)
libcpmt.lib(StlCompareStringA.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in realsense_node_factory.cpp.obj
libcpmt.lib(winapinls.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in realsense_node_factory.cpp.obj
libcpmt.lib(StlCompareStringW.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in realsense_node_factory.cpp.obj
libcpmt.lib(StlLCMapStringW.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in realsense_node_factory.cpp.obj
libcpmt.lib(winapisupp.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in realsense_node_factory.cpp.obj
   Creating library devel\lib\realsense2_camera.lib and object devel\lib\realsense2_camera.exp
```

**Comment by traversaro** [comment]
The problem is in https://github.com/IntelRealSense/librealsense/blob/5ff27fca5aaeec4736d6bb3bfb958fee82ee198b/third-party/realsense-file/CMakeLists.txt#L28, that seems to be compiled with the `/MT` flag, not sure why based on the official repo.

**Comment by Tobias-Fischer** [comment]
Thanks for the hint, Silvio. Let's see whether https://github.com/RoboStack/ros-noetic/pull/131/commits/2deeb861b544942f28857567528f6b4aa1f36d73 helps.

**Comment by Tobias-Fischer** [comment]
I'm giving up on this one. I don't know enough about the lib/dll building in Windows.
Latest errors are
```

cmd.exe /C "cd . && C:\Miniconda\conda-bld\ros_1621978556477\_build_env\Library\bin\cmake.exe -E vs_link_dll --intdir=CMakeFiles\realsense2.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~1\2019\ENTERP~1\VC\Tools\MSVC\1416~1.270\bin\HostX64\x64\link.exe /nologo @CMakeFiles\realsense2.rsp  /out:realsense2.dll /implib:realsense2.lib /pdb:realsense2.pdb /dll /version:2.45 /machine:x64 /INCREMENTAL:NO /DEF:C:\Miniconda\conda-bld\ros_1621978556477\work\ros-noetic-librealsense2\src\work\src\realsense.def  /DEF:C:\Miniconda\conda-bld\ros_1621978556477\work\ros-noetic-librealsense2\src\work\src\realsense.def  && cd ."
LINK: command "C:\PROGRA~2\MICROS~1\2019\ENTERP~1\VC\Tools\MSVC\1416~1.270\bin\HostX64\x64\link.exe /nologo @CMakeFiles\realsense2.rsp /out:realsense2.dll /implib:realsense2.lib /pdb:realsense2.pdb /dll /version:2.45 /machine:x64 /INCREMENTAL:NO /DEF:C:\Miniconda\conda-bld\ros_1621978556477\work\ros-noetic-librealsense2\src\work\src\realsense.def /DEF:C:\Miniconda\conda-bld\ros_1621978556477\work\ros-noetic-librealsense2\src\work\src\realsense.def /MANIFEST /MANIFESTFILE:realsense2.dll.manifest" failed (exit code 1120) with the following output:
   Creating library realsense2.lib and object realsense2.exp
ros_reader.cpp.obj : error LNK2019: unresolved external symbol "class rs2rosinternal::Time const rs2rosinternal::TIME_MAX" (?TIME_MAX@rs2rosinternal@@3VTime@1@B) referenced in function "public: virtual void __cdecl librealsense::ros_reader::disable_stream(class std::vector<struct librealsense::device_serializer::stream_identifier,class std::allocator<struct librealsense::device_serializer::stream_identifier> > const &)" (?disable_stream@ros_reader@librealsense@@UEAAXAEBV?$vector@Ustream_identifier@device_serializer@librealsense@@V?$allocator@Ustream_identifier@device_serializer@librealsense@@@std@@@std@@@Z)
ros_reader.cpp.obj : error LNK2019: unresolved external symbol "class rs2rosinternal::Time const rs2rosinternal::TIME_MIN" (?TIME_MIN@rs2rosinternal@@3VTime@1@B) referenced in function "private: class std::shared_ptr<class librealsense::device_serializer::serialized_frame> __cdecl librealsense::ros_reader::create_frame(class rosbag::MessageInstance const &)" (?create_frame@ros_reader@librealsense@@AEAA?AV?$shared_ptr@Vserialized_frame@device_serializer@librealsense@@@std@@AEBVMessageInstance@rosbag@@@Z)
ros_writer.cpp.obj : error LNK2001: unresolved external symbol "class rs2rosinternal::Time const rs2rosinternal::TIME_MIN" (?TIME_MIN@rs2rosinternal@@3VTime@1@B)
```

**Pull request closed without merging**
