### PR TITLE
Add rosbridge_suite

### PR DESCRIPTION
**Pull request by defunctzombie**

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
Thanks @defunctzombie

**Comment by defunctzombie** [comment]
@Tobias-Fischer Thank you for the fast merge! What's the release cadence for these packages (i.e. when can I mamba install it)?

**Comment by wolfv** [comment]
If the azure pipelines went through, it should already be possible

**Comment by wolfv** [comment]
https://dev.azure.com/robostack/ros_pipelines/_build

**Comment by wolfv** [comment]
Our linux-aarch64 builds currently do not work. Let me know if that's blocking you.

**Comment by defunctzombie** [comment]
I tried various forms of `mamba install ros-noetic-rosbridge-suite` or `rosbridge-server` or `rosbridge_suite` and all of them error with "nothing provides requested..."

I know rosbridge_suite is a metapackage, so maybe I need to do some more work to make that installable here?

```
(ros_env) ➜  ~ mamba install ros-noetic-rosbridge-server

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.21.2) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['ros-noetic-rosbridge-server']

conda-forge/osx-arm64                                       Using cache
conda-forge/noarch                                          Using cache
robostack/noarch                                              No change
robostack-experimental/noarch                                 No change
robostack/osx-arm64                                           No change
robostack-experimental/osx-arm64                              No change

Pinned packages:
  - python 3.9.*


Encountered problems while solving:
  - nothing provides requested ros-noetic-rosbridge-server
```

**Comment by Tobias-Fischer** [comment]
The issue is that most workflows are disabled at the moment @wolfv: https://github.com/RoboStack/ros-noetic/blob/master/.github/workflows/main.yml

Could you please have a look? At the moment linux-aarch64 appears to be twice in there, I'm not sure which one should be kept.

**Comment by defunctzombie** [comment]
@Tobias-Fischer Is the ask for me to look at the workflows or for @wolfv ?

**Comment by Tobias-Fischer** [comment]
For @wolfv

**Comment by Tobias-Fischer** [comment]
Kind ping @wolfv

**Comment by wolfv** [comment]
sorry folks! All it took was uncommenting the pipeline and things are running again: https://dev.azure.com/robostack/ros_pipelines/_build :)

**Pull request merged**
