### PR TITLE
Add aarch64 cross-platform build

### PR DESCRIPTION
**Pull request by Tobias-Fischer**

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
I couldn't figure out how to use exclude with arrays - it complains that it expects a string/int/bool. Any idea how to reduce the number of jobs?

**Comment by Tobias-Fischer** [comment]
It seems like the cross-platform build for aarch64 fails: https://github.com/RoboStack/ros-noetic/runs/2108324834
Any clue why @wolfv?

**Comment by wolfv** [comment]
For OS X arm64 you need to set the conda build sysroot

**Comment by wolfv** [comment]
conda_build_config.yaml

**Comment by wolfv** [comment]
https://github.com/mamba-org/boa-forge/blob/master/conda_build_config.yaml (sorry on mobile)

**Comment by Tobias-Fischer** [comment]
Looks like some odd stuff is going on for aarch:
```
/tmp/mambaf8p6sATTHdm: line 4: /usr/share/miniconda/conda-bld/ros_1615761685749/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python3.8: cannot execute binary file: Exec format error
Linking setuptools-52.0.0-py38hd43f75c_0
Linking pip-21.0.1-pyhd8ed1ab_0
/tmp/mambafGE1f6PRGSW: line 4: /usr/share/miniconda/conda-bld/ros_1615761685749/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python3.8: cannot execute binary file: Exec format error
Linking six-1.15.0-pyh9f0ad1d_0
/tmp/mambafQy2l4K0Bp5: line 4: /usr/share/miniconda/conda-bld/ros_1615761685749/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python3.8: cannot execute binary file: Exec format error
Linking pyparsing-2.4.7-pyh9f0ad1d_0
/tmp/mambaf9Akcr1DfR9: line 4: /usr/share/miniconda/conda-bld/ros_1615761685749/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python3.8: cannot execute binary file: Exec format error
Linking empy-3.3.4-pyh9f0ad1d_1
/tmp/mambaf38H27aOwOD: line 4: /usr/share/miniconda/conda-bld/ros_1615761685749/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python3.8: cannot execute binary file: Exec format error
Linking python-dateutil-2.8.1-py_0
/tmp/mambafpjpYS2cOcY: line 4: /usr/share/miniconda/conda-bld/ros_1615761685749/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python3.8: cannot execute binary file: Exec format error
Linking docutils-0.16-py38h2063c64_3
Linking pyyaml-5.4.1-py38h9544abe_0
Linking nose-1.3.7-py38h32f6830_1004
Linking ros-noetic-cpp-common-0.7.2-py38h148f926_3
Linking ros-noetic-rostime-0.7.2-py38h7b515c5_3
Linking ros-noetic-roscpp-traits-0.7.2-py38h60b0371_3
Linking ros-noetic-roscpp-serialization-0.7.2-py38h60b0371_3
Linking catkin_pkg-0.4.23-pyh9f0ad1d_0
/tmp/mambaf99cOuxwadh: line 4: /usr/share/miniconda/conda-bld/ros_1615761685749/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python3.8: cannot execute binary file: Exec format error
```

**Comment by wolfv** [comment]
Interesting, looks like we're getting arm64 python in host which is correct.
If python was in "build" it would be the correct executable format. I don't know how that should be done ...

**Comment by wolfv** [comment]
Maybe this package holds the key: https://github.com/conda-forge/cross-python-feedstock

**Comment by Tobias-Fischer** [comment]
Yes, it seems like: https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/
We'll need to add sth like this to our recipes
```yaml
requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
```

Will boa support this already? (sth like `sel(build_platform != target_platform): python`) etc.?)

**Comment by wolfv** [comment]
The selector you posted will work. I'm less sure about the jinja template (not sure we set this value, but maybe it works?) gotta try!

**Comment by wolfv** [comment]
I just tested quickly, and unfortunately that doesn't seem to work yet... I can look into it tomorrow morning!

**Comment by wolfv** [comment]
one quick hack might be to use `"{{ compiler('cross-python') }}"` because the compler packages use the same syntax to append `_linux-aarch64` etc.

**Comment by Tobias-Fischer** [comment]
Ahh .. I'll wait for you for a proper fix then.

**Comment by wolfv** [comment]
Okay, I just added this to boa: https://github.com/mamba-org/boa/pull/139 which should make this work.

**Comment by wolfv** [comment]
but... we also need to adjust vinca, right?

**Comment by Tobias-Fischer** [comment]
Yes that's right..

**Comment by wolfv** [comment]
Looks like there is still an issue with python ... I'll have a look tomorrow. Thanks for pushing on this!

**Comment by Tobias-Fischer** [comment]
Maybe https://github.com/RoboStack/vinca/commit/61305d8df7e1109d31e8d6f037a00a6efb0a8e4e will help?!?

**Comment by Tobias-Fischer** [comment]
Good news is that C++ packages seem to work anyhow.

By the way, I have no idea what is pulling in fcl ..

**Comment by wolfv** [comment]
Yep! Maybe :)

**Comment by Tobias-Fischer** [comment]
Yeah it seems indeed that the host python is used in places where the build python should be used instead. I guess it's somewhere in mamba?

**Comment by Tobias-Fischer** [comment]
Hi @wolfv - did you have a chance to look into this? If you point me in the right direction I could have a go, too.

**Comment by wolfv** [comment]
I only had a quick look with a different recipe that I tried to cross-compile locally (involving python and these cross-python tools). as far as I remember it seemed to work fine. Haven't really figured anything out here, yet, sorry!

I have just added some more proper handling for zip_keys in the conda_build_config to boa though (I don't think that's related to this here, though).

**Comment by Tobias-Fischer** [comment]
Hmm .. (for no good reason) I tried https://github.com/RoboStack/vinca/commit/8763cb529801b07b30882905ecb5ae9c7161029d but that didn't help.

**Comment by Tobias-Fischer** [comment]
Hi @wolfv - I digged some deeper here. Compilation still fails the first time around:

```bash
/tmp/mambafxCfhOy4oGo: line 4: /home/tobias/anaconda3/envs/robostackenv/conda-bld/ros_1619318124235/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python3.8: cannot execute binary file: Exec format error
Linking pip-21.1-pyhd8ed1ab_0
/tmp/mambafQLldJXrhOx: line 4: /home/tobias/anaconda3/envs/robostackenv/conda-bld/ros_1619318124235/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python3.8: cannot execute binary file: Exec format error
Linking six-1.15.0-pyh9f0ad1d_0
/tmp/mambafU9AWJ8PFyd: line 4: /home/tobias/anaconda3/envs/robostackenv/conda-bld/ros_1619318124235/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python3.8: cannot execute binary file: Exec format error
Linking pyparsing-2.4.7-pyh9f0ad1d_0
/tmp/mambafYNijETREfb: line 4: /home/tobias/anaconda3/envs/robostackenv/conda-bld/ros_1619318124235/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python3.8: cannot execute binary file: Exec format error
Linking empy-3.3.4-pyh9f0ad1d_1
/tmp/mambafM9dpZbJVOL: line 4: /home/tobias/anaconda3/envs/robostackenv/conda-bld/ros_1619318124235/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python3.8: cannot execute binary file: Exec format error
Linking python-dateutil-2.8.1-py_0
/tmp/mambaf5mVoTKFKrI: line 4: /home/tobias/anaconda3/envs/robostackenv/conda-bld/ros_1619318124235/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python3.8: cannot execute binary file: Exec format error
Linking docutils-0.17.1-py38h2063c64_0
Linking pyyaml-5.4.1-py38h9544abe_0
Linking nose-1.3.7-py38h32f6830_1004
Linking ros-noetic-cpp-common-0.7.2-py38h148f926_3
Linking ros-noetic-rostime-0.7.2-py38h7b515c5_3
Linking ros-noetic-roscpp-traits-0.7.2-py38h60b0371_3
Linking ros-noetic-roscpp-serialization-0.7.2-py38h60b0371_3
Linking catkin_pkg-0.4.23-pyh9f0ad1d_0
/tmp/mambafrY0nkMvGXZ: line 4: /home/tobias/anaconda3/envs/robostackenv/conda-bld/ros_1619318124235/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python3.8: cannot execute binary file: Exec format error
Linking ros-noetic-catkin-0.8.9-py38h60b0371_3
Linking ros-noetic-genmsg-0.5.16-py38h60b0371_3
Linking ros-noetic-genlisp-0.4.18-py38h60b0371_3
Linking ros-noetic-gennodejs-2.0.2-py38h60b0371_3
Linking ros-noetic-genpy-0.6.14-py38h60b0371_3
Linking ros-noetic-gencpp-0.6.5-py38h60b0371_3
Linking ros-noetic-geneus-3.0.0-py38h60b0371_3
Linking ros-noetic-message-runtime-0.4.13-py38h60b0371_3
Linking ros-noetic-message-generation-0.4.1-py38h60b0371_3
Linking ros-noetic-std-msgs-0.5.13-py38h60b0371_3
Linking ros-noetic-actionlib-msgs-1.13.1-py38h60b0371_3
Transaction finished

Starting build for ros-noetic-franka-msgs

source tree in: /home/tobias/anaconda3/envs/robostackenv/conda-bld/ros_1619318124235/work
export PREFIX=/home/tobias/anaconda3/envs/robostackenv/conda-bld/ros_1619318124235/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place
hold_placehold_placehold_placehold
export BUILD_PREFIX=/home/tobias/anaconda3/envs/robostackenv/conda-bld/ros_1619318124235/_build_env
export SRC_DIR=/home/tobias/anaconda3/envs/robostackenv/conda-bld/ros_1619318124235/work
/home/tobias/anaconda3/envs/robostackenv/conda-bld/ros_1619318124235/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python: 1: /home/tobias/anaconda3/envs/robostackenv/conda-bld/ros_1619318124235/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python: : not found
/home/tobias/anaconda3/envs/robostackenv/conda-bld/ros_1619318124235/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python: 1: /home/tobias/anaconda3/envs/robostackenv/conda-bld/ros_1619318124235/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python: cannot open : No such file
/home/tobias/anaconda3/envs/robostackenv/conda-bld/ros_1619318124235/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python: 1: /home/tobias/anaconda3/envs/robostackenv/conda-bld/ros_1619318124235/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python: ELF?@??:@8: not found
/home/tobias/anaconda3/envs/robostackenv/conda-bld/ros_1619318124235/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python: 1: /home/tobias/anaconda3/envs/robostackenv/conda-bld/ros_1619318124235/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python: Syntax error: word unexpected (expecting ")")
```

However, when re-running the build with `/home/tobias/anaconda3/envs/robostackenv/conda-bld/ros_1619318124235/work/conda_build.sh` it then compiles fine and uses the python in the build_env.

I've observed related behaviour previously in C++ projects, where the first time e.g. a find_package doesn't work, but then rerunning with conda_build.sh makes it work. It seems that some environment variables or something aren't properly set the first time around.

It would be great if you could have a look - should I also open an issue upstream in boa/mamba?

Many thanks!

**Comment by Tobias-Fischer** [comment]
My bet is that https://github.com/mamba-org/mamba/blob/48a43455e54218a676d21114965779a3298debbe/src/core/transaction_context.cpp#L13 needs fixing as it always uses the python in the host env - I think thus would get rid of these errors:
```
/tmp/mambafxCfhOy4oGo: line 4: /home/tobias/anaconda3/envs/robostackenv/conda-bld/ros_1619318124235/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python3.8: cannot execute binary file: Exec format error
```

**Comment by wolfv** [comment]
yeah I think what happens is that we (try) to compile the `py` files to `pyc` files when installing, and for that we use the Python of the prefix. However, if we're cross-compiling, we can't use the Python of the prefix to do this and thus it fails. Let me check what conda / conda-build does in this case.

**Comment by Tobias-Fischer** [comment]
Hmmm, doesn't the pyc compilation happen right at the end? Those errors occur even before the cmake invocation as far as I can tell.

**Comment by wolfv** [comment]
Yeah when installing a noarch python package, the .py files are compiled . This is before cmake starts, when the environment is created. Will have to see how conda handles this

**Comment by Tobias-Fischer** [comment]
@wolfv - we're getting closer, but not yet quite there ;).

The errors during linking are gone, but the other ones are still there:

```

Starting build for ros-noetic-franka-msgs

source tree in: /usr/share/miniconda/conda-bld/ros_1619469191201/work
export PREFIX=/usr/share/miniconda/conda-bld/ros_1619469191201/_h_env_placehold_
placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_
placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_
placehold_placehold_placehold
export BUILD_PREFIX=/usr/share/miniconda/conda-bld/ros_1619469191201/_build_env
export SRC_DIR=/usr/share/miniconda/conda-bld/ros_1619469191201/work
/usr/share/miniconda/conda-bld/ros_1619469191201/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python: 1: : not found
/usr/share/miniconda/conda-bld/ros_1619469191201/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python: 1: cannot open : No such file
/usr/share/miniconda/conda-bld/ros_1619469191201/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python: 1: ELF�@��:@8: not found
/usr/share/miniconda/conda-bld/ros_1619469191201/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python: 1: Syntax error: word unexpected (expecting ")")
```

**Comment by wolfv** [comment]
I think it's this line that fails: https://github.com/RoboStack/ros-noetic/blob/a54955e0324e6799c12d51f2760f559d5db02867/recipes/ros-noetic-libfranka/build_catkin.sh#L20 :)

**Comment by wolfv** [comment]
Tried to fix that line just now, let's see :)

**Comment by wolfv** [comment]
not yet!

**Comment by wolfv** [comment]
so, still getting a little bit closer, but unfortunately the catkin activation script is a bit problematic here. I think it sets (or unsets) LDFLAGS which seems to prevent the qemu-emulated python to run properly (similar to https://github.com/psf/black/issues/1827)

**Comment by wolfv** [comment]
@Tobias-Fischer if I change the conda activation script in ros-noetic-catkin /etc/conda/activate.d to read

```bash
if [[ "$CONDA_BUILD" == "1" && "$target_platform" != "$build_platform" ]]; then
	# ignore sourcing
	echo "Not activating ROS when cross-compiling";
else
	source $CONDA_PREFIX/setup.sh
fi
```

I can compile. We could make this change on the linux-aarch64 catkin package for now and see if it works?

**Comment by wolfv** [comment]
maybe better to use this fancy `"${CONDA_BUILD:0}"` syntax

**Comment by Tobias-Fischer** [comment]
Finally! @wolfv this is ready to go in my opinion - let's squash commits I guess. osx-arm64 next? ;)

**Comment by wolfv** [comment]
awesome! Did you end up patching catkin or did you find another way?

**Pull request merged**
