### PR TITLE
added usb-cam

### PR DESCRIPTION
**Pull request by sonelu**
Added usb-cam to all vinca files.

### CODE REVIEW

**Comment by sonelu** [comment]
I will try to see what are the problems for each build.

But in the meantime: linux-aarch64 was successful and this is the one I would need (for a Raspberry Pi). Is the build supposed to be pushed to the conda channel automatically? I can't see it yet...

**Comment by Tobias-Fischer** [comment]
It would be nice if you could at least fix linux-64. The packages only get uploaded to the channel if merged.

**Comment by sonelu** [comment]
I'm not sure what exactly is the difference between the `linux-64` and the `linux-aarch64` but it might have something to do with the header files for `video4linux`. Can we add `libv4l-dev` in the environment?

**Comment by Tobias-Fischer** [comment]
I think the difference is that linux-aarch64 uses syslinux 2.17, whereas linux-64 uses syslinux 2.12. We need to upgrade linux-64 to syslinux 2.17, but I recall that there were some issues with that. I'll investigate when I have some time.

**Pull request merged**
