### PR TITLE
Improve contributing experience and instruction

### PR DESCRIPTION
**Pull request by gftabor**
gitignored blanketly .sh and .bat files generated during build. This should be expanded to include files generated on other OS's if moving them to a dedicated build directory is too difficult.

Want to make a conda env file to specify the contributing environment instead of all the commands, waiting to hear back on if owners agree.

### CODE REVIEW

**Comment by gftabor** [comment]
Wait reviewing the other branches I see the github actions bot is committing all those .bat .sh files I was ignoring to the build branches. So maybe gitignoring them wasn't correct? Probably should have understood the whole CI pipeline before making that change.

**Comment by Tobias-Fischer** [comment]
We might be able to get around this by force adding the .bat and .sh files in the GitHub workflow.

**Comment by gftabor** [comment]
This should be good now unless there is something else.

**Comment by Tobias-Fischer** [comment]
LGTM - what do you think @wolfv @traversaro?

**Comment by gftabor** [comment]
closes #275

**Comment by traversaro** [comment]
> LGTM - what do you think @wolfv @traversaro?

Fine for me!

**Pull request merged**
