### PR TITLE
#47 Update to python 3.9

### PR DESCRIPTION
**Pull request by mstoelzle**
Address #47 and update to python 3.9

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
This probably needs a bump in build numbers, as well as fixes of quite a few updates of patches. We should also update the pinnings, see https://github.com/RoboStack/ros-noetic/pull/154

**Comment by wolfv** [comment]
Maybe we could take this as an opportunity to rebuild all packages?

**Comment by Tobias-Fischer** [comment]
Yes, agreed. At least desktop-full + moveit for all platforms.

**Comment by Tobias-Fischer** [comment]
Merging this in as I'm planning to do a rebuild of all packages soon-ish.

**Pull request merged**
