### PR TITLE
Add exotica packages

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
This builds fine, however I am not sure whether we should merge because pybind11_catkin and fcl_catkin are pulled in, and might lead to conflicts with the conda-forge packages.

/cc @wxmerkt

### CODE REVIEW

**Comment by wxmerkt** [comment]
Let's wait until fcl_catkin/ros-noetic-fcl is resolved and I get a chance to go over the other packages so we can do all at once - `exotica_core` without the plug-ins in `exotations` is of no use. I have a local workaround for pybind11_catkin so that might go by itself. I'll keep you posted, thank you for all the hard work and quick turnaround on fixes :-).

**Comment by Tobias-Fischer** [comment]
Agreed :)

**Comment by Tobias-Fischer** [comment]
Depends on https://github.com/ipab-slmc/exotica/pull/742

**Comment by Tobias-Fischer** [comment]
Any news on this @wxmerkt?

**Comment by wxmerkt** [comment]
I havent tested things with RoboStack recently. I might get back to it in July

**Comment by Tobias-Fischer** [comment]
Closing due to inactivity

**Pull request closed without merging**
