### PR TITLE
try migration

### PR DESCRIPTION
**Pull request by wolfv**
This is currently "the idea" to do migrations:

- add a specific file (migration.yaml) that contains the packages that are being migrated
- move pins in conda_build_config (or .ci_support/conda_forge_pinnings.yaml)

Vinca will download all built packages from the repodata.json file, and check which ones need migration. The ones needing migration are added to a copy of the `vinca.yaml` file. From that vinca.yaml file build scripts and build pipeline are generated. 

There is one problem currently, though:

We don't have a "full" graph, but rather a sparse graph. That means the topological sorting is not perfect right now. We'd need to create all recipes for the full graph and perform the topological sort on that, and then sparse it out afterwards. 

For the same reasons, vinca is currently building these packages sequentially. We'd need to do some more intelligent stuff to build them in parallel (e.g. figure out if a given package is in the subgraph of another package etc.).

Maybe in the future we should generate _all_ recipes to be able to use them for the graph in the azure pipelines part, and also have a list of the packages that we actually want to build. Then we can do some more advanced graph analysis to figure out the best order to build things in.

I actually don't know the best "algorithm" to have the most efficient pipeline... maybe someone has ideas here?

### CODE REVIEW

**Comment by wolfv** [comment]
Looks like there is partial success! :)

- I don't think we need to actually migrate jsk-topic-tools -- it only depends on opencv at runtime. We should probably _not_ use repodata.json to figure out what to migrate (instead use the full build information)
- It seems like we might also have to move the pin for libnetcdf

**Comment by wolfv** [comment]
So we definitely needed this one to be merged: https://github.com/conda-forge/flann-feedstock/pull/31

Not sure if the `proj` problem will be fixed by this as well.

**Comment by wolfv** [comment]
@Tobias-Fischer we could try to migrarte to vtk 9.0.3

**Comment by Tobias-Fischer** [comment]
Yep sounds like a plan. We might run into the same issue there as well though ..

**Comment by wolfv** [comment]
I guess this migration could help us over the next bump: https://github.com/conda-forge/vtk-feedstock/pull/210

**Comment by Tobias-Fischer** [comment]
Alright .. seems like this is ready for a test @wolfv :).

I needed to exclude some packages, but at the moment this seems to work quite nicely. What do we need to do to actually merge this in, without breaking all the other bits and pieces?

**Comment by Tobias-Fischer** [comment]
To keep track of the current ignored packages:
- lvr2 needs the qt migration to icu69
- swri-transform-util is incompatible with proj8 (https://github.com/swri-robotics/marti_common/issues/642)
- safety_limiter builds fine locally for me
- mrpt2 fails with several build errors around libudev and jsoncpp (unrelated to the migration)
- rtabmap builds fine after patching
- grid-map-filters depends on grid-map-ros depends on grid-map-cv (not being rebult) depends on cv-bridge which fails with `ib/libopencv_photo.so.4.5.2', needed by 'devel/lib/libgrid_map_filters.so', missing and no known rule to make it` (cmake file contains `set(libraries "grid_map_cv;/opt/conda/build_artifacts/ros-noetic-grid-map-cv_1634210768771/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/libopencv_photo.so.4.5.2")`) - it's actually a fault of https://github.com/ANYbotics/grid_map/blob/master/grid_map_cv/package.xml which does not specify a dependency on OpenCV but uses OpenCV in the CMakeLists.txt. - I added another option in vinca to force migrate for those cases that are not our fault

**Comment by Tobias-Fischer** [comment]
Okay, this is a lot more satisfying now. The build passes, and the packages that are ignored are ignored for a good reason that is out of our hands.

@wolfv - I think it's ready to tidy up a bit and get merged in (both here and vinca)?!?

**Comment by Tobias-Fischer** [comment]
Nice, I cleaned up `mrpt2` as well. 

Just `lvr2` and `swri-transform-utils` are ignored now - that needs changes in `qt` / upstream respectively.

**Comment by Tobias-Fischer** [comment]
I think we semi decided that migrations are probably not the way to go, as there might be some packages that transitively depend on other packages and would not be picked up by the migration. Also upstream builds all packages and does not guarantee any ABI compatibility etc.

I updated the pinnings and patches from this PR in https://github.com/RoboStack/ros-noetic/commit/5ae5d075358cf2f4cbc7c11dbed81c6c0efecf52 where I triggered a rebuild of desktop-full+moveit on all platforms. This is probably going to fail terribly, but we can patch our way through ;).

Closing here - many thanks for the effort with the migrator, @wolfv - I'm sure it will come in handy elsewhere :)

**Pull request closed without merging**
