### PR TITLE
add librealsense2 packages

### PR DESCRIPTION
**Pull request by baszalmstra**
Adds the `librealsense2`, `realsense2-camera`, and `realsense2-description` packages.

### CODE REVIEW

**Comment by wolfv** [comment]
ouch, getting hit by a mamba bug :)

**Comment by wolfv** [comment]
let me make release and we retry in a couple hours. sorry

**Comment by baszalmstra** [comment]
Haha no worries!

**Comment by baszalmstra** [comment]
And regarding using `librealsense` from `conda-forge`? Can I just add that to the `robostack.yaml` file? The only downside I see is that it doesn't build for windows, but we can fix that upstream.

**Comment by wolfv** [comment]
Release for mamba in the pipeline, but it'll take ~3 hours to propagate https://github.com/conda-forge/mamba-feedstock/pull/146

**Comment by wolfv** [comment]
I haven't personally tried that package yet but I trust @traversaro a lot :) I am sure if you guys want you can become co-maintainers of the conda-forge feedstock (https://github.com/conda-forge/librealsense-feedstock) to make sure that updates are merged quickly etc.

**Comment by Tobias-Fischer** [comment]
The Windows builds fail @baszalmstra - would be great if you could have a look (https://dev.azure.com/robostack/ros_pipelines/_build/results?buildId=3522&view=logs&j=2a05d173-1a26-5655-a01b-1fc4742df1ca&t=68e8f140-1776-5e5d-5257-4d245990caf9).

**Comment by Tobias-Fischer** [comment]
See also https://github.com/RoboStack/ros-noetic/pull/131

**Comment by wolfv** [comment]
@Tobias-Fischer I think we can simply remove it again from Windows. It was my fault, I merged too quickly

**Comment by baszalmstra** [comment]
I will make a PR to remove it from windows!

**Comment by baszalmstra** [comment]
Here you go: https://github.com/RoboStack/ros-noetic/pull/233

**Pull request merged**
