### PR TITLE
add ign packages to linux

### PR DESCRIPTION
**Pull request by raghavauppuluri13**

### CODE REVIEW

**Comment by wolfv** [comment]
looks like the `ign` package doesn't exist?

**Comment by raghavauppuluri13** [comment]
It was listed in the [package list ](https://robostack.github.io/noetic.html), should that be removed?

**Comment by traversaro** [comment]
I think that package is `ros-ign`, `ros-ign-bridge`, and so on so forth.

**Comment by raghavauppuluri13** [comment]
Ah. That'll do it. Thanks @traversaro

**Comment by Tobias-Fischer** [comment]
Triggered the build - let's see what happens.

**Comment by Tobias-Fischer** [comment]
Seems like osx is failing - check patch/add_dependencies.yaml and add gtest for the failing package.

**Comment by Tobias-Fischer** [comment]
Same error on Windows..

**Comment by Tobias-Fischer** [comment]
Any clue why the ci doesn't get triggered @wolfv?

**Comment by Tobias-Fischer** [comment]
ign-gazebo is currently not build for OSX and win, see https://github.com/conda-forge/libignition-gazebo-feedstock/issues/2

**Comment by Tobias-Fischer** [comment]
Cc @traversaro

**Comment by Tobias-Fischer** [comment]
This now fails because of incompatible ign versions - we are overwriting gazebo3 (citadel) with gazebo5 (edifice) as this is the first available version for win on conda-forge, but would need to do the same for transport & msgs (map from citadel to edifice). Any objections against this weird mapping?

**Comment by Tobias-Fischer** [comment]
This now fails because ros-noetic-pluginlib-1.13.0-py38h508dd2d_5 needs tinyxml2=8 ..

**Comment by Tobias-Fischer** [comment]
We probably need a full rebuild here, too :(

**Comment by traversaro** [comment]
> 
> 
> This now fails because of incompatible ign versions - we are overwriting gazebo3 (citadel) with gazebo5 (edifice) as this is the first available version for win on conda-forge, but would need to do the same for transport & msgs (map from citadel to edifice). Any objections against this weird mapping?
> 
> We should probably just do this for all platforms ..

Ok for me. When everything works and the amount of fixes is reduced, we can think of using the LTS (perhaps Fortress, see https://ignitionrobotics.org/docs/all/releases) or having alternatives, but for the time being just using the latest make more sense.

**Comment by Tobias-Fischer** [comment]
Hi @traversaro - just to confirm, this PR won’t be possible as Noetic only works with Fortress, but we don’t build Fortress for Windows anymore?

**Comment by traversaro** [comment]
> Hi @traversaro - just to confirm, this PR won’t be possible as Noetic only works with Fortress, but we don’t build Fortress for Windows anymore?

Yes, I am afraid unless we make sure that Fortress packages works on Windows, this PR can't work.

**Comment by Tobias-Fischer** [comment]
Ok thanks Silvio! I assume getting things to work won’t be trivial, so let’s close here. If there are interested people we could guide them in the right direction.

**Comment by Tobias-Fischer** [comment]
Hi @raghavauppuluri13 - feel free to let us know if you are still interested in this for Windows - we can point you in the right direction if you would like to contribute.

**Pull request merged**
