### PR TITLE
Add pybind11 catkin

### PR DESCRIPTION
**Pull request by PeterMitrano**
This is just a guess at where this is supposed to go. Is there a way for me to test these kinds of things locally?

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
Thanks @PeterMitrano! I just created a contributing file that describes how to test these changes locally: https://github.com/RoboStack/ros-noetic/blob/master/CONTRIBUTING.md

I'll merge this for now so we can see if it succeeds anyway. If it does, would you mind creating another PR to also build this package on the other platforms? Our aim is feature parity across the different platforms.

**Comment by Tobias-Fischer** [comment]
So it was running fine and crashed with an unrelated error (https://dev.azure.com/roboforge/ros_pipelines/_build/results?buildId=863&view=logs&j=81cddaf1-5c1e-5d1f-1cca-e3198579e5a9&t=efbb9686-a87b-55b7-a312-870cf9f87002). However, this package needs patching anyway. It downloads pybind11 and builds it. Instead, we should use the pybind11 provided in conda-forge to avoid ABI incompatibilities.

@wolfv: Do you have any idea what the best way of doing this will be? How can we add the dependency on pybind11 in the case of this repository? pybind11 is not contained as dependency in the package.xml ..

**Comment by wolfv** [comment]
I just fixed the issue that was in boa, sorry for that! https://dev.azure.com/roboforge/ros_pipelines/_build/results?buildId=863&view=logs&j=6d42b290-185e-5671-4df8-3f01588a2875&t=9f5516ad-427d-596e-b134-7617dab89b9b

Yeah that is a really tough question! I think we might want to have a step in vinca where we can inject additional dependencies? I was thinking of that before as well... 

We could have a file in `patch` that is a dependencies.yaml and contains something like conda-forge repodata patches. E.g. in this case:


```yaml
pybind11_catkin:
   add:
      build_export_depend:
        - 'pybind11'
   remove: ['zlib']
```

What do you think?

**Comment by Tobias-Fischer** [comment]
That sounds great to me. Would you be happy to implement sth like that?

**Comment by wolfv** [comment]
yeah, i can take care of that

**Pull request merged**
