### PR TITLE
Add ecl

### PR DESCRIPTION
**Pull request by wolfv**

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
See https://github.com/stonier/ecl_core/issues/111

**Comment by traversaro** [comment]
The Windows failure seems to be related to https://github.com/stonier/ecl_lite , not https://github.com/stonier/ecl_core . In particular, it seems that `ECL_HAS_WIN_TIMERS` is not defined at the preprocessor level and so the function is not defined: https://github.com/stonier/ecl_lite/blob/7f03e914d8aa6cb816f12b82e9b793d19c6ebe3c/ecl_time_lite/src/lib/date.cpp#L14 . As there is a `#cmakedefine ECL_HAS_WIN_TIMERS` in https://github.com/stonier/ecl_lite/blob/7f03e914d8aa6cb816f12b82e9b793d19c6ebe3c/ecl_time_lite/include/ecl/time_lite/config.hpp.in#L85 , probably it is sufficient to set `ECL_HAS_WIN_TIMERS` at the CMake level, if possible during the invocation, or just by patching the CMakeLists.txt

**Comment by traversaro** [comment]
The macOS failure may be trickier, it seems that the related class is not enabled if we are on Apple, see https://github.com/stonier/ecl_core/blob/b8e8e10e0f5abfc63aeeac88000bacd0a85e1f9c/ecl_devices/include/ecl/devices/socket_client_pos.hpp#L22 .

**Comment by Tobias-Fischer** [comment]
No one has asked for ecl in particular - closing

**Pull request closed without merging**
