### PR TITLE
build all previously supported noetic packages

### PR DESCRIPTION
**Pull request by v4hn**
yes, a number of them are definitely broken by now but if we don't build them, you don't see the breakage and various of them are still fine.

As proposed in https://github.com/RoboStack/ros-noetic/issues/287#issuecomment-1264534810 .

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
I remember I think I previously tracked down the packages that worked by using
`boa .... --continue-on-failure`
And then checking which packages had been built in the `conda-bld` directory, and using these to refine the list.

**Comment by v4hn** [comment]
> I remember I think I previously tracked down the packages that worked by using `boa .... --continue-on-failure` And then checking which packages had been built in the `conda-bld` directory, and using these to refine the list.

You lost me there. So where do you want to go with this pr from here?

**Comment by Tobias-Fischer** [comment]
Hi @v4hn - sorry for that!

Background to my suggestion: Checking what still builds and what does not will take a long time by iterating via this PR, as it can take hours to find out what the next package is that is broken. Instead it is faster to iterate locally.

Suggestion itself:
1. Clone the repo
2. `ln -s vinca_linux.yaml vinca.yaml`
3. `mamba install -y pip rospkg libmambapy rich networkx "catkin_pkg>=0.4.16" "ruamel.yaml>=0.16.6" "rosdistro>=0.8.0" "empy>=3.3.4" boa`
4. `pip install git+https://github.com/RoboStack/vinca.git@master --no-deps`
5. `vinca --multiple`
6. `boa build recipes -m ./.ci_support/conda_forge_pinnings.yaml -m ./conda_build_config.yaml --continue-on-failure`
7. `cd $CONDA_PREFIX/conda-bld/$CONDA_SUBDIR`
8. Parse the output of `ls` to extract the package names - those are the packages that built without issues. I used to have a script for that, but can't find it at the moment ..

Does that make more sense?

**Comment by v4hn** [comment]
It does, but I proposed to do that in CI. I don't have the cycles to work through the broken packages either, but I was complaining that your setup does not even build the packages that still work or show what things fail. Does that require much more than adding `--continue-on-failure` somewhere?

**Comment by Tobias-Fischer** [comment]
It shows which package is broken in the CI, but one by one. I’m not sure if there’sa way to amend the CI to show all broken packages at once @wolfv ?

**Comment by Tobias-Fischer** [comment]
This is not going to happen, and users now have the ability to request individual packages they would like to be added in RoboStack.

**Comment by v4hn** [comment]
Hi Tobias,

> and users now have the ability to request individual packages

For completeness, did you set up a new interface somewhere to do that or do you mean they can create PRs here?

**Comment by Tobias-Fischer** [comment]
Hi, if you open a new issue in this repository there’s now a template in place to request packages and specify the platforms.

**Pull request closed without merging**
