### PR TITLE
adding dynamixel_sdk

### PR DESCRIPTION
**Pull request by sonelu**

### CODE REVIEW

**Comment by sonelu** [comment]
Not sure why the Windows build fails. Could be due to this:
```
#if defined(__linux__)
#include "port_handler.h"
#include "port_handler_linux.h"
#elif defined(__APPLE__)
#include "port_handler.h"
#include "port_handler_mac.h"
#elif defined(_WIN32) || defined(_WIN64)
#define WINDLLEXPORT
#include "port_handler.h"
#include "port_handler_windows.h"
```
(in [here](https://github.com/ROBOTIS-GIT/DynamixelSDK/blob/c7e1eb71c911b87f7bdeda3c2c9e92276c2b4627/c%2B%2B/src/dynamixel_sdk/port_handler.cpp#L19).

Do we have other environment macros defined for Windows from `_WIN32` and `_WIN64`?

**Comment by wolfv** [comment]
should we ignore the Windows failure or is the package supposed to work on Windows as well?

**Comment by sonelu** [comment]
> 



> should we ignore the Windows failure or is the package supposed to work on Windows as well?

In principle it should, yes. You could use a USB dongle like the [U2D2](https://emanual.robotis.com/docs/en/parts/interface/u2d2/) and then communicate with them. Frankly I don't know anybody that does that with a robot, but I could see that being used for students to control Dynamixel servos with ROS on a Windows machine.

**Comment by sonelu** [comment]
@wolfv then probably we can ignore the win build. I've seen that the previous versions that we build only linux and mac: [anaconda](https://anaconda.org/robostack/ros-noetic-dynamixel-sdk/files).

**Comment by sonelu** [comment]
I'll remove the package from the windows vinca. Should keep things clean.

**Pull request merged**
