### PR TITLE
add swri-console to the rebuild list

### PR DESCRIPTION
**Pull request by ruben-arts**
We would like to use the SwRI console again in our python 3.9 environments. 

I'm not sure if we also need the SwRI-console-util or any of the other packages but the ros package doesn't seem to depend on them so I tried it first like this.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
It tries to build plotjuggler and rviz as well, probably as new versions have been released. The patches need updating - any chance you could do that @ruben-arts?

**Comment by ruben-arts** [comment]
@Tobias-Fischer I updated the rviz patch by using `git-rebase-patch` of the old patch and then regenerating a patch file. This seems to work when I test locally. The plotjuggler didn't change anything to the patch so I'm hoping the ci will just work :sweat_smile:

**Comment by Tobias-Fischer** [comment]
It looks like it removed a part of the patch that we still need (for osx so it doesn't error here).

**Comment by ruben-arts** [comment]
I think it did it better now.

**Review by Tobias-Fischer — APPROVED** [review]

**Pull request merged**
