### PR TITLE
Bump version ros-distro-mutex

### PR DESCRIPTION
**Pull request by Tobias-Fischer**

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
I guess we don't really want to do this .. otherwise we need to rebuild all packages.

Shall we just manually remove the existing package, and then re-generate it?

**Comment by wolfv** [comment]
how about bumping the build number? then we can remove the one with the lower build number

**Comment by Tobias-Fischer** [comment]
But doesn't the run export mean only this version can be installed?

**Comment by wolfv** [comment]
Actually the build string completely removes the build number so it shouldn't matter for resolution. However I'm not sure if we'll rebuild the package . Maybe we can also do something to vinca to force a rebuild

**Comment by wolfv** [comment]
btw we should also be able to bump the version to 0.1.1

**Comment by wolfv** [comment]
I checked vinca, and I think it should rebuild when the build number changes.

**Comment by Tobias-Fischer** [comment]
Oh gosh, embarrassing, why didn't I think of that? Thanks Wolf, happy to merge.

**Comment by wolfv** [comment]
let's see what happens! 👍

**Comment by Tobias-Fischer** [comment]
Cool. Do we need to delete the old version?

**Comment by wolfv** [comment]
Nope, it was automatically overwritten it seems :)

**Comment by wolfv** [comment]
I just checked the repodata and it looks good

**Pull request merged**
