### PR TITLE
Packages for jupyterlab-ros

### PR DESCRIPTION
**Pull request by hbcarlos**
Should I leave lines 54-58 uncommented?

ping @wolfv

### CODE REVIEW

**Comment by wolfv** [comment]
looks like the franka packages are also missing at this point

**Comment by hbcarlos** [comment]
Thank you so much @Tobias-Fischer!!

**Comment by Tobias-Fischer** [comment]
Happy to merge as is, but I'd be even happier if we add these packages also to the other platforms :). Are you okay doing that @hbcarlos?

**Comment by hbcarlos** [comment]
Yes, I'm going to add the packages to the other platforms and also rebase to squash my commits a little bit.
Thanks again for the help!

**Comment by Tobias-Fischer** [comment]
We can squash and merge when merging in :)

**Comment by hbcarlos** [comment]
Should I add also the `osx_arm64` and `linux_aarch64`?

**Comment by hbcarlos** [comment]
Any idea what is going on with the windows build?

**Comment by hbcarlos** [comment]
Thanks, @wolfv! Should I remove franka from win?

**Pull request merged**
