### PR TITLE
Add plotjuggler to linux

### PR DESCRIPTION
**Pull request by gftabor**
Useful ros plotting utility.
Also this issue makes it tedious to compile locally inside robostack catkin environment
https://github.com/facontidavide/PlotJuggler/pull/483

### CODE REVIEW

**Comment by wolfv** [comment]
Hmm, unfortunately I don't know why the compilation fails. I had a quick look – it seems like it's not properly linking to Qt?

**Comment by Tobias-Fischer** [comment]
You might have to clone this repo and checkout the correct branch: https://github.com/facontidavide/plotjuggler-release

It might be that the release version differs in some way.

**Comment by gftabor** [comment]
Ya I think the problem was me thinking galactic can currently build with its current patch. Actually reading the Cmake I linked above along with the patch shows they don't match. This patch just happened many months ago and have not triggered a galactic build since.
Update from November last year
https://github.com/facontidavide/PlotJuggler/commit/4a4d82d2692b4536af8b0017da63dbd7c0396c9e#diff-285967ff03f5fb94705efb5bebd763944b7591d7b23062885f4a4823ed10d1bf
that changes the dependency for ZMQ to be handled through Cmake

**Comment by gftabor** [comment]
And the current build error is the CI telling me I was stupid to manually edit the patch files...

**Comment by gftabor** [comment]
This last commit builds completely on my linux test machine but elfutils, the added dependency is linux only.
https://anaconda.org/conda-forge/elfutils

**Comment by gftabor** [comment]
Ya I am not really sure where to go from here. Different OSes have different errors.
**Arm linux** has what looks like
https://stackoverflow.com/questions/57446579/executable-says-line-1-elf-not-found-when-starts
**Macos**, Undefined symbol from QT
**macos-arm64** is missing a dependency for its fancy stack trace debugging utility dependency (backward-cpp wants binutils) It seems like this could be dropped from build and just not have nice stack traces? Seems like plot juggler does this for windows builds.
Here is blocking binutils error https://github.com/conda-forge/binutils-feedstock/issues/56
Here is backward being turned off for windows https://github.com/facontidavide/PlotJuggler/blob/main/CMakeLists.txt#L252
**Windows** seems like it is failing to link with QT? similar to Macos

**Pull request merged**
