### PR TITLE
Added CRAS packages

### PR DESCRIPTION
**Pull request by peci1**
Added packages published by CTU CRAS mostly on https://gihtub.com/ctu-vras . I tried adding comments with the name of the "maintainer" of the added packages who should be contacted in case of some problems. If this is not intended, I'll remove the comments.

### CODE REVIEW

**Comment by peci1** [comment]
I'm facing [an issue](https://github.com/conda-forge/geographiclib-cpp-feedstock/issues/12) with geographiclib on aarch64, probably due to cross-compilation. I've temporarily disabled it for this architecture, but I'd like to have it when possible.

**Comment by Tobias-Fischer** [comment]
Thanks @peci1!

If you need magnetometer_compass on aarch64, the build would likely succeed on the main branch as there we build natively instead of cross-compiling (as in PRs).

**Comment by peci1** [comment]
Thanks. There seems to be something wrong with boa on the master branch pipelines...

**Comment by Tobias-Fischer** [comment]
Fixed :)

**Pull request merged**
