### PR TITLE
add gridmap

### PR DESCRIPTION
**Pull request by wolfv**
Let's see if PR building works :)

### CODE REVIEW

**Comment by wolfv** [comment]
hmm, looks like the gridmap demos link with Qt Widgets, and that needs to link with GL.

**Comment by Tobias-Fischer** [comment]
Can we use https://github.com/RoboStack/ros-noetic/blob/master/patch/dependencies.yaml ?

**Comment by wolfv** [comment]
yep, trying that right now! Otherwise we can also skip either the one demo that fails, or the demos package altogether

**Comment by Tobias-Fischer** [comment]
Ready to be merged? Looks like the pipeline works nicely

**Pull request merged**
